### ISSUE TITLE
UI: Tooltip

### ISSUE THREAD

**Issue by KotAleksei** [Panenco/panenco-ui#102]
if set content as JSX, the position isn't calculated correctly (white-space rule as a reason) need to find another way of handling correct position for tooltip
<img width="621" alt="Screenshot 2021-08-18 at 10 50 48" src="https://user-images.githubusercontent.com/34914550/129859579-8529fef7-0af1-45c2-a0e7-da7de9f2960c.png">

**Comment by vozbrann** [comment]
Refactor to react-tooltip? (https://github.com/wwayne/react-tooltip)

**Comment by vlacher12** [comment]
Tooltip is removed already
