### ISSUE TITLE
UI: Accordion

### ISSUE THREAD

**Issue by klevytskyi** [Panenco/panenco-ui#13]
- Title not in a Text component
- - size doest change if changing global size
- - how to add clickable icons in the title?

- Primary: double blue border on focus
![image](https://user-images.githubusercontent.com/2786291/92734581-56c05f00-f381-11ea-9dfc-4d16beb01dcd.png)

- Secondary: focus border has an offset
![image](https://user-images.githubusercontent.com/2786291/92734601-5aec7c80-f381-11ea-9796-030cc18aec86.png)

**Comment by KotAleksei** [comment]
1. Title is the Text component.
2. Default value for Text component is `s`, so if you want to see how will be looks title of accordion, you can change `s` size in the root styles. 
3. Basically we implemented default behavior for iconLeft and iconRight props (you can check how it will be) + `icons` property gives you the opportunity to add as many icons as you want.

Primary: set normalizer in your application or set rule for all buttons `outline: none`
Secondary: need to check.
