### ISSUE TITLE
NotificationContainer positioning not working

### ISSUE THREAD

**Issue by sebastiaanviaene** [Panenco/panenco-ui#137]
` <NotificationContainer style={{ marginBottom: 70 }} position="bottom-left" />` 

this is how I defined the NotificationContainer but it doesn't have any effect on the positioning. In another project i'm using the 1.1.11 version of this package and it's working correctly there

I see in the sourcecode that no props are passed to the ToastContainer, that could be the issue

**Comment by kaliahinartem** [comment]
#158 opened pr for this

**Comment by vlacher12** [comment]
NotificationContainer is removed already
