### ISSUE TITLE
Table: use of checkbox in first column 

### ISSUE THREAD

**Issue by bertdk** [Panenco/panenco-ui#24]
I used a checkbox in the first column of a table to select a row. The row was too long to fit on the screen so it started with '>'. This combined with a checkbox gave an issue. The checkbox jumped to the next row like a <br/> would do
<img width="737" alt="Screenshot 2020-11-03 at 03 13 05" src="https://user-images.githubusercontent.com/62398560/100356166-25a41200-2ff3-11eb-93f0-8ebb3eb7df86.png">

**Comment by KotAleksei** [comment]
fixed
