### ISSUE TITLE
Remove 'Dark Mode' button from docs

### ISSUE THREAD

**Issue by vozbrann** [Panenco/panenco-ui#279]
panenco.ui is not supporting dark mode

**Comment by KotAleksei** [comment]
@vozbrann 
Are you correctly set up the theme in your project?

**Comment by vozbrann** [comment]
> @vozbrann Are you correctly set up the theme in your project?

No, I am not using a dark theme in my project. 

I am talking about the "Dark Mode" button in the panenco.ui docs. We should hide it because we don't have proper support for dark mode for now.

**Comment by vlacher12** [comment]
Modes are removed already
