### ISSUE TITLE
DateInput changes suggestion

### ISSUE THREAD

**Issue by vozbrann** [Panenco/panenco-ui#282]
Suggestion: use selects
<img width="620" alt="image" src="https://user-images.githubusercontent.com/39827437/169091856-3934ba90-0978-4003-8235-a749342b7bfa.png">
https://jeffmcammond.com/react-select-datepicker/?path=/story/welcome--page

**Comment by lazzystep** [comment]
# Should be discussed and agreed with Oleksandr Kanskyi

## Only after that we should either close or start work on it
