### ISSUE TITLE
UI: TextInput

### ISSUE THREAD

**Issue by klevytskyi** [Panenco/panenco-ui#3]
- Blue box around text when typing
- If use autofill in from chrome, the background is not fully colored
![image](https://user-images.githubusercontent.com/2786291/92733033-dfd69680-f37f-11ea-8e7f-967c5bbc3922.png)
- If using with validation scheme there is an offset at the right end (only on large screens). In this offset, an error icon appears when the field is invalid
![image](https://user-images.githubusercontent.com/62398560/92095412-f015d100-edd5-11ea-93cf-79c16cd3f37d.png)
![image](https://user-images.githubusercontent.com/2786291/92733164-08f72700-f380-11ea-8c9c-994009e5d2fb.png)
- The background color of the container from the title + field is white, maybe make it transparent
![image](https://user-images.githubusercontent.com/2786291/92733214-19a79d00-f380-11ea-9832-e67ab57d94b5.png)
- The red error border and the orange secondary button border look very much alike

**Comment by KotAleksei** [comment]
2. fixed 
others: check the design system please
