### ISSUE TITLE
ResizeObserver implementation

### ISSUE THREAD

**Issue by vlacher12** [Panenco/panenco-ui#325]
We should to replace [resize-observer-polyfill](https://www.npmjs.com/package/resize-observer-polyfill) by smth else, like [use-resize-observer](https://github.com/ZeeCoder/use-resize-observer)

Last time `resize-observer-polyfill` was published 4 years ago

**Comment by vlacher12** [comment]
Let's fix it, cause we face a lot of error from `resize-observer-polyfill`

**Comment by vozbrann** [comment]
@vlacher12 `ResizeObserver` is used only in the deprecated `ResponsiveTable`

**Comment by vlacher12** [comment]
But we still get these errors in active products
