### ISSUE TITLE
Inconsistent input background color

### ISSUE THREAD

**Issue by vozbrann** [Panenco/panenco-ui#395]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/39827437/212307580-de01ee4a-cb8c-471b-b8d6-0fabfbf67013.png">

TextInput - transparent
SelectInput - white

**Comment by vozbrann** [comment]
@vlacher12 Should be transparent?

**Comment by vlacher12** [comment]
yes

**Comment by vlacher12** [comment]
but i'd ask Oleksandr to be sure

**Comment by vlacher12** [comment]
@vozbrann Background color should be white by default 
from Oleksandr
