### ISSUE TITLE
Stop `Select` component support or redesign to something like MUI or React Select

### ISSUE THREAD

**Issue by vozbrann** [Panenco/panenco-ui#402]
+inherit accessibility
<img width="574" alt="image" src="https://user-images.githubusercontent.com/39827437/212332804-5270d6ca-2fad-491a-a151-5123039b5d4d.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/39827437/212332836-1659e677-c984-49ca-a95a-f3370d6893b3.png">

**Comment by vlacher12** [comment]
@vozbrann Closed?
