### ISSUE TITLE
Create single AccordionComponent

### ISSUE THREAD

**Issue by vlacher12** [Panenco/panenco-ui#413]
Primary and Secondary accordions are exactly the same, they just have different colors. We need to merge them into single component with `color` prop (primary, secondary)

**Comment by vozbrann** [comment]
@vlacher12 They are not the same. Not only color is different:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/39827437/213404670-0c9c5c4d-df83-4eb2-b36e-95fb91ea75b1.png">
