### ISSUE TITLE
`focus` state overflow

### ISSUE THREAD

**Issue by vlacher12** [Panenco/panenco-ui#426]
Adjust styling to fix `focus` state 
![image](https://user-images.githubusercontent.com/24992556/212920439-75cc5188-98ed-4170-a3f0-763faa0152ad.png)

**Comment by vozbrann** [comment]
@vlacher12 
ant.design behavior: 
<img width="156" alt="image" src="https://user-images.githubusercontent.com/39827437/214823605-de449fde-9942-46dc-b225-a676dfb8b5ef.png">

So I think we can live it like is

**Comment by vlacher12** [comment]
Could you share link?

**Comment by vozbrann** [comment]
@vlacher12 
https://ant.design/components/button
