### ISSUE TITLE
UI: general usage

### ISSUE THREAD

**Issue by klevytskyi** [Panenco/panenco-ui#5]
- Readme for table
- Storybook run in the readme
- New component idea: switch with 2 labels (currently I used the slider with 2 values but the drag and drop functionality is not expected behavior for this kind of component
![image](https://user-images.githubusercontent.com/2786291/92733622-7e62f780-f380-11ea-9787-8e876d5b0e25.png)

**Comment by KotAleksei** [comment]
1. done
2. done
3. we will add Toggle component.
