### ISSUE TITLE
Theme colors are not specified

### ISSUE THREAD

**Issue by sebastiaanviaene** [Panenco/panenco-ui#52]
I just had to look into the source code to see that the button is using the variable 'accent500' as a background color. What is the reasoning behind this and why is it not reflected in the docs?

**Comment by vlacher12** [comment]
https://www.figma.com/file/AAIW0jTTQNYKAOckbmUbpG/PanencoUI?node-id=688%3A355


Indeed, I'll add it to the doc

**Comment by vozbrann** [comment]
This issue can be covered by introducing extensive theme customization with a palette and a color prop

**Comment by lazzystep** [comment]
# Desired behaviour:
- Have a documentation of colors variable names and default values of those inside PUI.
- Other colors that you will add/overwrite in your project should be documented with a link in general readme to readme of place where you modify/add colors
- developer naming convention should be discussed and approved

### Will be closed after PanencoUI update
