### ISSUE TITLE
UI: Table

### ISSUE THREAD

**Issue by lazzystep** [Panenco/panenco-ui#76]
after toggle loading plus icon becomes hidden

<img width="927" alt="Toggle Loading" src="https://user-images.githubusercontent.com/25006856/128174660-72a733ed-7c22-41db-b7d5-a5bb05e1a301.png">

**Comment by vozbrann** [comment]
Stop supporting the ResponsiveTable component: https://github.com/Panenco/panenco-ui/issues/398
