### ISSUE TITLE
UI: Icon

### ISSUE THREAD

**Issue by klevytskyi** [Panenco/panenco-ui#9]
- No email icon
- Coloring of icons has no effect
- - I used a workaround by adding some scss

```
svg,
symbol {
  [fill]:not([fill='none']):not([fill^='url(']) {
    fill: currentColor;
  }
  [stroke]:not([stroke='none']):not([stroke^='url(']) {
    stroke: currentColor;
  }
}
```

**Comment by KotAleksei** [comment]
1. we will expand our icon base 
2. after that how you added the last rules to your `root styles file` should be ok.
